version: '3.9'

services:
  db:
    image: postgres:15
    container_name: nutva-postgres
    restart: always
    environment:
      POSTGRES_USER: nutva_user
      POSTGRES_PASSWORD: nutva_pass
      POSTGRES_DB: nutva_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: NutvaCms.API/Dockerfile
    container_name: nutva-api
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=nutva_db;Username=nutva_user;Password=nutva_pass
    volumes:
      - ./NutvaCms.API/wwwroot/uploads:/app/wwwroot/uploads

volumes:
  postgres_data:
