name: Deploy Nutva Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Check if backend is healthy
        id: health
        run: |
          ssh -o StrictHostKeyChecking=no -p 2245 ntva@demo.nutva.uz "
            curl -f http://localhost:5000/swagger/index.html
          " || echo "unhealthy=true" >> $GITHUB_OUTPUT

      - name: dotnet build test
        id: buildcheck
        run: |
          cd NutvaBackend
          dotnet restore
          dotnet build --configuration Release
          echo "build_ok=true" >> $GITHUB_OUTPUT

      - name: Deploy only if unhealthy and build is successful
        if: steps.health.outputs.unhealthy == 'true' && steps.buildcheck.outputs.build_ok == 'true'
        run: |
          echo "Backend is unhealthy and build passed. Deploying..."
          ssh -o StrictHostKeyChecking=no -p 2245 ntva@demo.nutva.uz << 'EOF'
            set -e
            cd ~/NutvaBackend
            git pull origin main
            docker compose down
            docker compose up --build -d
          EOF
